### ISSUE TITLE
Update to new version(s)?

### ISSUE THREAD

**Issue by NikeboyHU** [cFerg/MineJava#3]
Hi! You're working newest versions update?
MC:PC -> 1.10
MC:PE -> 0.15.0

You share me any info?

**Comment by cFerg** [comment]
Hey, I'm currently working on updating, yes

Almost finished fixing the java.io , java.Lang,  java.util , and few other libraries... then I'll add in the newest features

I'm currently at work, but I have been working on it off time (just never pushed them to github)

Actually - in past few days, i set up a newer host for the website, a slack, a dubtrack, a forums, and other integrations

**Comment by NikeboyHU** [comment]
Oh, okey, thank you, i'm waiting to new perfectly java style server softwer, developed by you :)

**Comment by cFerg** [comment]
Status update: Internet was out for a week ;-; | Just got it back

However, I've almost finished re-formatting all the files and adding needed imports - Then I can push more updates.
